# Generated by Django 6.1 on 2026-09-13 01:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('es_publico', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('contenido', models.TextField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado_animo', models.CharField(max_length=25)),
                ('es_publica', models.BooleanField(default=False)),
                ('nivel_importancia', models.IntegerField()),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('enlace_referencia', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario_personal.categoria')),
                ('etiquetas', models.ManyToManyField(blank=True, to='diario_personal.etiqueta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario_personal.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=25)),
                ('estado_nuevo', models.CharField(max_length=25)),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentario', models.TextField(blank=True, max_length=100)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario_personal.entradadiario')),
            ],
        ),
    ]
