# Generated by Django 6.1 on 2026-09-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario_personal', '0002_alter_categoria_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradadiario',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='entradadiario',
            name='enlace_referencia',
        ),
        migrations.RemoveField(
            model_name='entradadiario',
            name='es_publica',
        ),
        migrations.RemoveField(
            model_name='entradadiario',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='es_publico',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=25, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='entradadiario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='entradadiario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='nombre',
            field=models.CharField(max_length=25, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=25, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
    ]
